In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import f1_score
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.cluster import MiniBatchKMeans, KMeans


data = pd.read_csv('synthetic_control.csv', sep='\s+', header = None)
data

0        1        2        3        4        5        6        7   \
0    28.7812  34.4632  31.3381  31.2834  28.9207  33.7596  25.3969  27.7849   
1    24.8923  25.7410  27.5532  32.8217  27.8789  31.5926  31.4861  35.5469   
2    31.3987  30.6316  26.3983  24.2905  27.8613  28.5491  24.9717  32.4358   
3    25.7740  30.5262  35.4209  25.6033  27.9700  25.2702  28.1320  29.4268   
4    27.1798  29.2498  33.6928  25.6264  24.6555  28.9446  35.7980  34.9446   
5    25.5067  29.7929  28.0765  34.4812  33.8000  27.6671  30.6122  25.6393   
6    28.6989  29.2101  30.9291  34.6229  31.4138  28.4636  35.9115  32.9058   
7    30.9493  34.3170  35.5674  34.8829  30.6691  35.2667  35.8950  25.9022   
8    35.2538  34.6402  35.7584  28.5510  25.6518  29.6442  31.9400  35.9086   
9    29.1734  31.5089  33.1944  35.6177  31.5890  35.1223  28.6222  34.3145   
10   35.2623  35.6805  31.0851  30.2589  24.1366  27.0766  25.7770  33.1482   
11   26.7115  24.0969  30.0213  29.9423  31.5460  33.7673  26.7519  28.7294   
12   34.2296  32.8783  24.2457  26.9036  25.8677  34.0545  30.8923  28.7287   
13   30.1451  28.2025  26.5217  26.3509  35.4694  33.4757  32.4387  35.9166   
14   24.0543  33.0039  35.4925  28.5634  28.7661  32.5147  29.9813  24.3169   
15   28.1944  30.7994  33.9010  26.7178  27.5378  28.0809  32.5500  33.7445   
16   26.0377  28.3229  27.8169  26.0755  35.8300  26.7637  30.3826  33.3847   
17   35.4815  26.8952  34.7511  36.0264  26.2202  30.3771  24.7539  29.3497   
18   27.0997  31.5199  30.8038  28.5932  26.6983  32.5261  24.7359  30.7745   
19   29.4965  28.1316  29.4459  31.4876  32.5261  34.8466  33.0777  24.4932   
20   25.7946  33.9116  25.3323  24.4300  26.9818  25.3804  25.3411  30.1135   
21   33.4655  30.7767  35.9042  35.4448  27.8881  24.0044  28.7063  24.5398   
22   31.7006  31.3466  34.3405  33.6582  34.7008  29.0794  27.8264  24.3558   
23   32.2613  27.3329  30.6940  27.3329  33.7185  30.3973  32.7784  30.8898   
24   30.2137  33.5576  34.5969  35.8645  32.4596  30.8967  24.4473  30.1050   
25   34.2127  25.6690  24.0059  31.6246  28.0684  25.6268  28.1628  28.8987   
26   33.0777  32.9058  26.4093  25.7531  25.1916  24.8237  30.9287  31.1634   
27   26.1229  27.5393  27.8286  32.7989  32.2584  33.4875  29.1620  31.4509   
28   34.1522  28.7753  32.6374  28.1430  31.2739  26.1861  30.5754  25.8647   
29   26.0528  26.6546  25.6327  30.1965  30.5483  34.0332  32.3961  33.7864   
..       ...      ...      ...      ...      ...      ...      ...      ...   
570  34.0736  24.1785  28.9501  31.1336  35.5046  30.9853  33.0707  24.3272   
571  28.6358  35.5542  28.9894  26.8827  30.2795  35.2942  33.5495  32.7218   
572  34.1790  27.0398  29.3324  31.8299  25.8882  28.2443  33.8510  26.0531   
573  34.2888  32.7982  32.1346  28.6556  27.8811  32.3877  28.4602  29.2266   
574  26.5290  28.9472  27.3931  35.8638  26.5434  25.9661  24.0228  25.9705   
575  31.1949  32.0851  32.9315  28.0141  31.3973  32.6458  32.7516  33.0957   
576  34.9160  29.6600  33.0619  27.9406  33.8525  33.0916  24.6089  28.0563   
577  27.5947  33.8099  33.0553  29.3985  29.1936  35.8311  26.2125  29.3493   
578  25.5353  35.6152  29.1837  35.0056  34.5186  25.2750  30.6125  34.7221   
579  35.6838  28.1033  24.0815  33.7974  24.9717  28.8807  35.8513  27.6538   
580  30.4227  31.0532  32.5713  31.8354  34.5932  30.7723  28.6126  34.6369   
581  26.4567  26.5110  35.3419  32.0608  32.2632  31.0069  35.1903  32.0153   
582  31.7568  28.7952  24.4050  34.0100  31.7494  25.6077  32.9976  30.9059   
583  25.7762  30.9915  32.8919  35.7440  28.5234  31.3657  33.4875  30.3309   
584  32.3256  31.8243  27.8797  25.9253  25.1788  28.7210  27.6487  28.0020   
585  33.9193  27.1004  34.7235  24.7800  26.3807  32.5125  28.1004  33.5069   
586  33.5073  31.6525  27.3711  27.3017  31.1560  35.7246  30.7980  34.2307   
587  34.4533  34.0717  31.2140  34.2102  28.5297  33.8077  28.6978  31.4028   
588  33.2066  31.0572  31.0873  30.0793  30.1869  25.5423  2

In [4]:
x_train = data
x_train

0        1        2        3        4        5        6        7   \
0    28.7812  34.4632  31.3381  31.2834  28.9207  33.7596  25.3969  27.7849   
1    24.8923  25.7410  27.5532  32.8217  27.8789  31.5926  31.4861  35.5469   
2    31.3987  30.6316  26.3983  24.2905  27.8613  28.5491  24.9717  32.4358   
3    25.7740  30.5262  35.4209  25.6033  27.9700  25.2702  28.1320  29.4268   
4    27.1798  29.2498  33.6928  25.6264  24.6555  28.9446  35.7980  34.9446   
5    25.5067  29.7929  28.0765  34.4812  33.8000  27.6671  30.6122  25.6393   
6    28.6989  29.2101  30.9291  34.6229  31.4138  28.4636  35.9115  32.9058   
7    30.9493  34.3170  35.5674  34.8829  30.6691  35.2667  35.8950  25.9022   
8    35.2538  34.6402  35.7584  28.5510  25.6518  29.6442  31.9400  35.9086   
9    29.1734  31.5089  33.1944  35.6177  31.5890  35.1223  28.6222  34.3145   
10   35.2623  35.6805  31.0851  30.2589  24.1366  27.0766  25.7770  33.1482   
11   26.7115  24.0969  30.0213  29.9423  31.5460  33.7673  26.7519  28.7294   
12   34.2296  32.8783  24.2457  26.9036  25.8677  34.0545  30.8923  28.7287   
13   30.1451  28.2025  26.5217  26.3509  35.4694  33.4757  32.4387  35.9166   
14   24.0543  33.0039  35.4925  28.5634  28.7661  32.5147  29.9813  24.3169   
15   28.1944  30.7994  33.9010  26.7178  27.5378  28.0809  32.5500  33.7445   
16   26.0377  28.3229  27.8169  26.0755  35.8300  26.7637  30.3826  33.3847   
17   35.4815  26.8952  34.7511  36.0264  26.2202  30.3771  24.7539  29.3497   
18   27.0997  31.5199  30.8038  28.5932  26.6983  32.5261  24.7359  30.7745   
19   29.4965  28.1316  29.4459  31.4876  32.5261  34.8466  33.0777  24.4932   
20   25.7946  33.9116  25.3323  24.4300  26.9818  25.3804  25.3411  30.1135   
21   33.4655  30.7767  35.9042  35.4448  27.8881  24.0044  28.7063  24.5398   
22   31.7006  31.3466  34.3405  33.6582  34.7008  29.0794  27.8264  24.3558   
23   32.2613  27.3329  30.6940  27.3329  33.7185  30.3973  32.7784  30.8898   
24   30.2137  33.5576  34.5969  35.8645  32.4596  30.8967  24.4473  30.1050   
25   34.2127  25.6690  24.0059  31.6246  28.0684  25.6268  28.1628  28.8987   
26   33.0777  32.9058  26.4093  25.7531  25.1916  24.8237  30.9287  31.1634   
27   26.1229  27.5393  27.8286  32.7989  32.2584  33.4875  29.1620  31.4509   
28   34.1522  28.7753  32.6374  28.1430  31.2739  26.1861  30.5754  25.8647   
29   26.0528  26.6546  25.6327  30.1965  30.5483  34.0332  32.3961  33.7864   
..       ...      ...      ...      ...      ...      ...      ...      ...   
570  34.0736  24.1785  28.9501  31.1336  35.5046  30.9853  33.0707  24.3272   
571  28.6358  35.5542  28.9894  26.8827  30.2795  35.2942  33.5495  32.7218   
572  34.1790  27.0398  29.3324  31.8299  25.8882  28.2443  33.8510  26.0531   
573  34.2888  32.7982  32.1346  28.6556  27.8811  32.3877  28.4602  29.2266   
574  26.5290  28.9472  27.3931  35.8638  26.5434  25.9661  24.0228  25.9705   
575  31.1949  32.0851  32.9315  28.0141  31.3973  32.6458  32.7516  33.0957   
576  34.9160  29.6600  33.0619  27.9406  33.8525  33.0916  24.6089  28.0563   
577  27.5947  33.8099  33.0553  29.3985  29.1936  35.8311  26.2125  29.3493   
578  25.5353  35.6152  29.1837  35.0056  34.5186  25.2750  30.6125  34.7221   
579  35.6838  28.1033  24.0815  33.7974  24.9717  28.8807  35.8513  27.6538   
580  30.4227  31.0532  32.5713  31.8354  34.5932  30.7723  28.6126  34.6369   
581  26.4567  26.5110  35.3419  32.0608  32.2632  31.0069  35.1903  32.0153   
582  31.7568  28.7952  24.4050  34.0100  31.7494  25.6077  32.9976  30.9059   
583  25.7762  30.9915  32.8919  35.7440  28.5234  31.3657  33.4875  30.3309   
584  32.3256  31.8243  27.8797  25.9253  25.1788  28.7210  27.6487  28.0020   
585  33.9193  27.1004  34.7235  24.7800  26.3807  32.5125  28.1004  33.5069   
586  33.5073  31.6525  27.3711  27.3017  31.1560  35.7246  30.7980  34.2307   
587  34.4533  34.0717  31.2140  34.2102  28.5297  33.8077  28.6978  31.4028   
588  33.2066  31.0572  31.0873  30.0793  30.1869  25.5423  2

In [5]:
x_train = preprocessing.minmax_scale(x_train)

In [6]:
x_train

array([[ 0.39736691,  0.54472471,  0.32197847, ...,  0.56261696,
         0.41359997,  0.46371947],
       [ 0.07393608,  0.11087291,  0.17065087, ...,  0.5766661 ,
         0.51502452,  0.47598042],
       [ 0.61505834,  0.35413672,  0.12447574, ...,  0.57105933,
         0.47595605,  0.51566799],
       ..., 
       [ 0.9893379 ,  0.15717689,  0.43604691, ...,  0.28164872,
         0.30077847,  0.33805713],
       [ 0.04449471,  0.03821111,  0.19976571, ...,  0.33611911,
         0.22303895,  0.33783565],
       [ 0.8592969 ,  0.36935252,  0.34655936, ...,  0.21427405,
         0.20317378,  0.22847335]])

In [7]:
# Compute clustering with Means
k_means = KMeans(init='k-means++', n_clusters=6, n_init=10)
k_means.fit(x_train)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=6, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [8]:
# Compute clustering with MiniBatchKMeans
batch_size = 45

mbk = MiniBatchKMeans(init='k-means++', n_clusters=6, batch_size=batch_size,
                      n_init=10, max_no_improvement=10, verbose=0)
mbk.fit(x_train)

MiniBatchKMeans(batch_size=45, compute_labels=True, init='k-means++',
        init_size=None, max_iter=100, max_no_improvement=10, n_clusters=6,
        n_init=10, random_state=None, reassignment_ratio=0.01, tol=0.0,
        verbose=0)

In [9]:
y_pred_Kmeans = k_means.predict(x_train)
y_pred_Mbk = mbk.predict(x_train)

In [22]:
y_pred_Kmeans

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 3, 4, 3, 3, 4, 4, 4, 3, 4, 3, 3, 3, 3, 3, 3,
       3, 3, 4, 3, 3, 3, 3, 3, 4, 3, 4, 3, 4, 4, 4, 4, 4, 3, 3, 4, 4, 4, 4,
       3, 4, 4, 3, 4, 3, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 3, 4, 3, 3, 4, 4, 3,
       3, 4, 4, 3, 4, 3, 3, 4, 4, 4, 4, 4, 3, 4, 3, 4, 3, 3, 3, 4, 3, 4, 4,
       3, 4, 4, 4, 3, 4, 4, 3, 4, 4, 3, 3, 4, 3, 3, 4, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 5,

In [11]:
y_pred_Mbk

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 4, 3, 4, 4, 0, 0, 0, 4, 0, 4, 4, 4, 4, 4, 4,
       4, 4, 3, 4, 4, 4, 4, 4, 3, 4, 3, 4, 0, 3, 0, 3, 3, 4, 4, 3, 3, 0, 0,
       4, 3, 3, 4, 3, 4, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 4, 3, 3, 4,
       4, 0, 0, 4, 3, 3, 4, 0, 0, 3, 3, 3, 3, 3, 4, 3, 4, 4, 4, 0, 4, 0, 3,
       4, 0, 0, 3, 4, 0, 3, 4, 3, 0, 4, 4, 3, 4, 4, 3, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2,